### PR TITLE
Use create-hash / Bump version / Bump dependencies

### PR DESCRIPTION
**Pull request by sublimator**
Use create-hash, which will use native node modules where possible, or pure javascript implementations when constrained by the browser environment. Also take the opportunity to update the dependencies and bump the version.

### CODE REVIEW

**Comment by clark800** [comment]
What are the performance benchmarks?

**Comment by sublimator** [comment]
Obviously native impls will trump pure ja

**Comment by clark800** [comment]
Would be interesting to see the difference regardless

LGTM

**Comment by sublimator** [comment]
Yeah, should do/have done some benchmarks eh?

**Pull request merged**
